### ISSUE TITLE
Add "PS Remote Play" to the capture target.

### ISSUE THREAD

**Issue by slowkuma** [Haytsir/Genshin-Paisitioning-App#3]
우선 좋은 프로그램 만들어 주신것에 감사 드립니다.

* capture 의 대상에 대하여 `원신` 뿐만 아니라 [PS Remote Play](<https://remoteplay.dl.playstation.net/remoteplay/lang/kr/ps5_win.html>) 도 대상으로 추가 가능 하신가요?
PC 사양 으로 인하여 PC 에서 플레이 하지 못하고 Remote 로만 할 수 있는 사람들을 위함 입니다.
`PS Remote Play` 의 경우는 전체화면으로도 동작 할수 있으며 창크기가 자유롭게 변경 되지만 16:9 레터박스가 생성 됩니다.
화면 해상도가 16:9 가 아니면 전체화면이라도 레터박스가 생성되는건 마찬가지 입니다.
그러니 당장은 16:9 전체화면에서만 동작 하는 것으로 하면 되겠습니다.
레터박스 환경에서 포지션 대한 아이디어는 있으니 일단 가능 여부만 문의 드립니다.

제가 사용 하는 환경에서 맞추어 보려 하는 것 입니다.
(죄송합니다. 꾸벅)

검토 부탁 드립니다.

**Comment by Haytsir** [comment]
현재 원신 윈도우 핸들을 찾고, 캡쳐하는 부분까지, 캡쳐에 관련한 거의 대부분의 로직은 [cvAutoTrack](https://github.com/GengGode/cvAutoTrack)에 들어있습니다.

[cvAutoTrack](https://github.com/GengGode/cvAutoTrack)에서 윈도우 핸들/dx훅에 관한 부분은 라이브러리 밖으로 노출하지 않아서 개인용 포크버전을 만들어 사용하셔야 합니다.
